### ISSUE TITLE
how to configure authentication routes?

### ISSUE THREAD

**Issue by henry-ht** [cedvdb/x_router#2]
first, it's a very good job you do here, thanks for this plugin.

I have several doubts but I will focus on this one.

I have three routes that make up the authentication: 1 login, 2 forgot password and 3 sign up.

How can I navigate between these three views without authentication?

would you give me an example

Thank you.

**Comment by cedvdb** [comment]
`router.goTo` ?

**Comment by henry-ht** [comment]
true the back button does not work when I navigate with goTo, it exits the application

**Comment by cedvdb** [comment]
I'd suggest using another package like go_router as it's been endorsed by the flutter team, this one is mainly used internally by us and we are short on time, so we do not have time for proper Q/A.

To answer your question there is 2 back buttons in general and their behavior is different, if you mean the phone back button, then you can use a `BackButtonListener` which is a flutter class, if you meant the app back button this is used to navigate the stack of pages and should work correctly as of now.
